### ISSUE TITLE
Please add 3.5

### ISSUE THREAD

**Issue by huachuman** [biobootloader/wolverine#2]
I think 3.5 would be worth adding because even though it may not get things right as much as 4, it's still way cheaper and GPT-4 is still only available to a small number of people.

**Comment by cat-stack-boop** [comment]
Just get rid of the comment in the code? See here:

  response = openai.ChatCompletion.create(
        # model="gpt-3.5-turbo",
        model="gpt-4",
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        temperature=1.0,
    )
    
    So make it:  response = openai.ChatCompletion.create(
       model="gpt-3.5-turbo",
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        temperature=1.0,
    )

**Comment by biobootloader** [comment]
added!
