### ISSUE TITLE
3.5 - has anyone tested?

### ISSUE THREAD

**Issue by samrahimi** [biobootloader/wolverine#3]
First of all, this is f-ing brilliant and I'm going to be using it frequently... I'm wondering if the agent is able to do  its job properly when you drop down to 3.5 turbo, because i have an idea that involves the automated deployment of wolverine at scale, and gpt4 is too expensive for that purpose - will 3.5 work or is it a waste of time?

**Comment by 0xcha05** [comment]
I had trouble with 3.5 so I forked wolverine, this does a decent job with 3.5

https://github.com/0xcha05/elixir

**Comment by biobootloader** [comment]
3.5 will likely have more trouble, the prompt might need to be reworked. But it would be good to have as an option

**Comment by brandino** [comment]
I tried with 3.5 and was seeing wolverine crash. Didn't spend much time trying to figure it out though.

**Comment by biobootloader** [comment]
I've added 3.5. It sometimes fails to return valid json, which will cause a crash.
