### ISSUE TITLE
reorder venv commands in README

### ISSUE THREAD

**Issue by epylar** [biobootloader/wolverine#7]
Hello,

I noticed an issue in the README file. The current instructions are:

```
python3 -m venv venv
pip install -r requirements.txt
source venv/bin/activate
```

I believe the correct order should be:

```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```

**Comment by biobootloader** [comment]
ah, yes! thanks!

**Comment by sanaaouxe** [comment]
> Hello,
> 
> I noticed an issue in the README file. The current instructions are:
> 
> ```
> python3 -m venv venv
> pip install -r requirements.txt
> source venv/bin/activate
> ```
> 
> I believe the correct order should be:
> 
> ```
> python3 -m venv venv
> source venv/bin/activate
> pip install -r requirements.txt
> ```

wolverine.py

**Comment by sanaaouxe** [comment]
[downloadfile.PDF](https://github.com/biobootloader/wolverine/files/11225694/downloadfile.PDF)

**Comment by sanaaouxe** [comment]
https://github.com/biobootloader/wolverine/issues/7#issuecomment-1500963823
